### ISSUE TITLE
Possibility of sponsoring this project

### ISSUE THREAD

**Issue by Fabioni** [grishka/NearDrop#115]
Hey, I really like this project and would enjoy seeing it continued. Therefore, I would like to ask if there is the possibility to sponsor your work?

**Comment by grishka** [comment]
There isn't one because I already have everything money can buy and enough savings to last me many years.

But even setting that aside, I don't like the idea of getting sponsored for my hobby projects because that would create a relationship where I would owe something in return to people who pay me. I see this as limiting my freedom of what I can do with my projects.
